# Generated by Django 3.1.4 on 2021-01-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_oder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oder',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='oder',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
