# Generated by Django 3.1.4 on 2021-01-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210129_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oder',
            name='price',
            field=models.IntegerField(),
        ),
    ]
